on: [push]
name: Build
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@02a151ada4993995686f9ed4f1be7cfbb229e56f
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: nix build
        run: nix build
